# Generated by the varis-cli release workflow (scripts/homebrew-formula.sh
# in AugustineOjeh/varis-cli). Don't edit it here: each release replaces it.
class Varis < Formula
  desc "Publish services that AI agents discover and pay to use"
  homepage "https://github.com/AugustineOjeh/varis-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/AugustineOjeh/varis-cli/releases/download/v0.2.1/varis-darwin-arm64.tar.gz"
      sha256 "d854ceeeebaf79b7c9b6249a577cd678cc334a6b9fb2d2ee56bb5755f67165d9"
    end
    on_intel do
      url "https://github.com/AugustineOjeh/varis-cli/releases/download/v0.2.1/varis-darwin-x64.tar.gz"
      sha256 "369424d09931966217d77e327b0721d02dc4b72a91bc03600d2891020d57045a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/AugustineOjeh/varis-cli/releases/download/v0.2.1/varis-linux-arm64.tar.gz"
      sha256 "d4fae0fb59387ff945f2d5b5661791f1b160529cc4b0f948f8a65ca326d47d7d"
    end
    on_intel do
      url "https://github.com/AugustineOjeh/varis-cli/releases/download/v0.2.1/varis-linux-x64.tar.gz"
      sha256 "16788af64a21d8a6659739df31b0d37165ae07b01224a3957abe052fb7a0eeaa"
    end
  end

  def install
    bin.install "varis"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/varis --version").strip
  end
end
