# Generated by the varis-cli release workflow (scripts/homebrew-formula.sh
# in usevaris/varis-cli). Don't edit it here: each release replaces it.
class Varis < Formula
  desc "Publish services that AI agents discover and pay to use"
  homepage "https://github.com/usevaris/varis-cli"
  version "0.3.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/usevaris/varis-cli/releases/download/v0.3.4/varis-darwin-arm64.tar.gz"
      sha256 "58eb69f01714bfb2cc86ee1618114299572bc2bd62328c0caf603a6f185405da"
    end
    on_intel do
      url "https://github.com/usevaris/varis-cli/releases/download/v0.3.4/varis-darwin-x64.tar.gz"
      sha256 "069c3b80817064a4fb7503e41a5c8bf7c1f8192df74fc820bf4792febcbd49fb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/usevaris/varis-cli/releases/download/v0.3.4/varis-linux-arm64.tar.gz"
      sha256 "2d28973644f120eb4dfb92dca2dd9b3fbb4b3489f32aa0bc75d16fa7b824da51"
    end
    on_intel do
      url "https://github.com/usevaris/varis-cli/releases/download/v0.3.4/varis-linux-x64.tar.gz"
      sha256 "e2a5fc664895cd04363455130be37ba920996b1f7d9d2b322ae51061208c75d8"
    end
  end

  def install
    bin.install "varis"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/varis --version").strip
  end
end
