# Generated by the varis-cli release workflow (scripts/homebrew-formula.sh
# in usevaris/varis-cli). Don't edit it here: each release replaces it.
class Varis < Formula
  desc "Publish services that AI agents discover and pay to use"
  homepage "https://github.com/usevaris/varis-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/usevaris/varis-cli/releases/download/v0.3.1/varis-darwin-arm64.tar.gz"
      sha256 "6cfa630e7158da14dbc20bee01afb651fb3716ae12f9ef357a726f8c8361214e"
    end
    on_intel do
      url "https://github.com/usevaris/varis-cli/releases/download/v0.3.1/varis-darwin-x64.tar.gz"
      sha256 "10c62bea516be7981acdbcd4aca2035354c10973810c1778e46fae610eb58355"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/usevaris/varis-cli/releases/download/v0.3.1/varis-linux-arm64.tar.gz"
      sha256 "fcd95ed6171e166dee82765dc0bb04a8931d0129650b117984a8906ea1caec0b"
    end
    on_intel do
      url "https://github.com/usevaris/varis-cli/releases/download/v0.3.1/varis-linux-x64.tar.gz"
      sha256 "cdaa48e7dd70255ee5f1c40c825756667023be864a40e0d8118b0b4c7ceb5ba6"
    end
  end

  def install
    bin.install "varis"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/varis --version").strip
  end
end
